# Generated by Django 4.2.7 on 2023-11-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "delete_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Datetime"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Deleted status"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Active status"
                    ),
                ),
                (
                    "line1",
                    models.CharField(max_length=100, verbose_name="line 1"),
                ),
                (
                    "city_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="city name"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        max_length=100, verbose_name="country name"
                    ),
                ),
                (
                    "zip_code",
                    models.IntegerField(unique=True, verbose_name="zip code"),
                ),
                (
                    "weather",
                    models.CharField(max_length=150, verbose_name="weather"),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "delete_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Datetime"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Deleted status"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Active status"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        max_length=50, verbose_name="tracking number"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(max_length=50, verbose_name="carrier"),
                ),
                (
                    "article_name",
                    models.CharField(
                        max_length=100, verbose_name="article name"
                    ),
                ),
                (
                    "article_quantity",
                    models.PositiveIntegerField(
                        verbose_name="article quantity"
                    ),
                ),
                (
                    "article_price",
                    models.FloatField(verbose_name="article price"),
                ),
                ("sku", models.CharField(max_length=50, verbose_name="sku")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scanned", "scanned"),
                            ("in-transit", "in-transit"),
                            ("delivery", "delivery"),
                            ("transit", "transit"),
                            ("inbound-scan", "inbound-scan"),
                        ],
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "receiver_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_shipments",
                        to="tracking.location",
                        verbose_name="receiver address",
                    ),
                ),
                (
                    "sender_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="tracking.location",
                        verbose_name="sender address",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
            },
        ),
    ]
